:header: Octopus Build Integration Gradle Plugin
= {header}
:toc:
:toclevels: 4
:version-label: 2.0-SNAPSHOT

== Purpose of the Plugin

`Octopus Build Integration Gradle Plugin` adds the ability to export the list of components your project depends on into a TeamCity build parameter.

The list is formed based on:

* explicitly defined components;
* gradle dependencies.

== Applying the Plugin
.settings.gradle.kts
[source,kotlin]
----
pluginManagement {
    plugins {
        id("org.octopusden.octopus-build-integration") version extra["octopus-build-integration.version"] as String
    }
}
----

.settings.gradle
[source,groovy]
----
pluginManagement {
    plugins {
        id 'org.octopusden.octopus-build-integration' version settings['octopus-build-integration.version']
    }
}
----

.build.gradle.kts
[source,kotlin]
----
plugins {
    id("org.octopusden.octopus-build-integration")
}
----


.build.gradle
[source,groovy]
----
plugins {
    id 'org.octopusden.octopus-build-integration'
}
----

[IMPORTANT]
====
It is important to use the plugin version parameter name **exactly as specified in the documentation**:
`octopus-build-integration.version`

This ensures that TeamCity automatically injects the latest version of the plugin for each build.
====

== Plugin Configuration
=== DSL Reference
[cols="3,6,3", options="header"]
|===
| DSL Element
| Description
| Override via `-P`

| `add(name = "", version = "")`
| Explicitly adds a component to the exported dependencies list.
| No

| `scan.setEnabled()`
| Enables or disables Gradle dependency scanning

Default value is false.
| Yes

`buildIntegration.dependencies.scan.enabled`

| `scan.setComponentsRegistryUrl()`
| URL of the Components Registry service.
| Yes

`buildIntegration.dependencies.scan.componentsRegistryUrl`

| `scan.setProjects()`
| Regular expression used to filter resolved artifacts by module name.

Default value is ".+".
| Yes

`buildIntegration.dependencies.scan.projects`

| `scan.setConfigurations()`
| Regular expression used to select Gradle configurations from which dependencies are extracted.

Default value is "runtime.+".
| Yes

`buildIntegration.dependencies.scan.configurations`

| `setTeamCityParameter()`
| Name of the TeamCity parameter to which the plugin will write the resulting dependency list.

Default value is "DEPENDENCIES"
| Yes

`buildIntegration.dependencies.teamCityParameter`
|===

=== Configuring

If you want to explicitly add a component, it can be done as follows:

.build.gradle.kts | build.gradle
[source,kotlin]
----
buildIntegration {
    dependencies {
        add("component_a", "1.0.0")
        add("component_b", "1.2.0")
    }
}
----

If you need to include Gradle dependencies, you can configure scanning as follows:

.build.gradle.kts | build.gradle
[source,kotlin]
----
buildIntegration {
    dependencies {
        scan {
            // only project "service-a"
            setProjects("service-a")

            // service-a or service-b
            setProjects("(service-a|service-b)")

            // exclude legacy-* projects
            setProjects("^(?!legacy-).+")
        }
    }
}

----

.build.gradle.kts | build.gradle
[source,kotlin]
----
buildIntegration {
    dependencies {
        scan {
            // include only runtimeClasspath and compileClasspath dependencies
            setConfigurations("(runtimeClasspath|compileClasspath)")

            // include only test dependencies
            setConfigurations("test.+")
        }
    }
}
----

'''
The latest version of the plugin is  {version-label}